let playerName = "Mario";
let currentLives = 3;
const level1 = 25;
const level2 = 30;
const level3 = 45;
let midValue = 0;
let du = 0;
midValue = (level1 + level2 + level3) / 3;
du = (level1 + level2 + level3) % 3;
console.log("Giá trị trung bình coin của 3 level: " + midValue);
console.log("Số coin dư khi chia giá trị trung bình cho 3 là: " + du);
